import type { Metadata } from 'next';
import { Roboto, Playfair } from 'next/font/google';
import '@/styles/globals.css';

const roboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin'],
  weight: ['100', '300', '400', '500', '700', '900'],
  style: ['normal'],
});

const playfair = Playfair({
  variable: '--font-playfair',
  subsets: ['latin'],
  weight: ['400', '500', '700', '900'],
  style: ['normal'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${playfair.variable}`}>
        {children}
      </body>
    </html>
  );
}
